//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_HISTORY
    {
        public int ID { get; set; }
        public int TASK_ID { get; set; }
        public System.DateTime DATE_EVENT { get; set; }
        public int OPERATION { get; set; }
    
        public virtual TASK TASK { get; set; }
    }
}
